In [37]:
import pandas as pd
import warnings; warnings.simplefilter('ignore')
import numpy as np
from datetime import datetime, timedelta


now = datetime.now()
if now.weekday() >= 5:  # 5: Saturday, 6: Sunday
    days_to_subtract = now.weekday() - 4
    today = now.date() - timedelta(days=days_to_subtract)
    today_str = (now - timedelta(days=days_to_subtract)).strftime("%d-%m-%Y")
else:
    if now.hour < 18:
        today = now.date() - timedelta(days=1)
        today_str = (now - timedelta(days=1)).strftime("%d-%m-%Y")
    else:
        today = now.date()
        today_str = now.strftime("%d-%m-%Y")

In [51]:
gunluk_ozet = pd.read_parquet("../data/parquet/gunluk_ozet.parquet")
haftalık_ozet = pd.read_parquet("../data/parquet/haftalık_ozet.parquet")
port_all = pd.read_parquet("../data/parquet/port_all.parquet")
hisse_gunluk = pd.read_parquet("../data/parquet/hisse_gunluk.parquet")
port_all_today = port_all.query("date == @today")
price_data = pd.read_parquet("../data/parquet/data_daily.parquet")
price_hourly = pd.read_parquet("../data/parquet/data_hourly.parquet")

In [55]:
mask = price_hourly['date'].dt.hour == 9
price_hourly.loc[mask, 'open'] = price_hourly['close'].shift(1)[mask]

In [60]:
hisse_gunluk

,date,ticker,h_q,a_p_b,d_q_c,open,close,d_%,a_%,a_a_b,t_v,d_r_p,a_r_p,d_ur_p,a_ur_p,d_p,a_p
0,2023-09-19,KLSER,56.0,88.35,56.0,86.00,89.80,4.4,1.6,4947.6,5028.8,0.0,0.0,212.8,81.2,212.8,81.2
1,2023-09-20,KLSER,28.0,88.35,-28.0,91.00,86.30,-5.2,-2.3,4947.6,2416.4,46.2,46.2,-131.6,-57.4,-85.4,-11.2
2,2023-09-21,KLSER,28.0,88.35,0.0,87.00,90.35,3.9,2.3,4947.6,2529.8,0.0,46.2,93.8,56.0,93.8,102.2
3,2023-09-22,KLSER,28.0,88.35,0.0,90.65,95.75,5.6,8.4,4947.6,2681.0,0.0,46.2,142.8,207.2,142.8,253.4
4,2023-09-25,KLSER,28.0,88.35,0.0,99.05,105.30,6.3,19.2,4947.6,2948.4,0.0,46.2,175.0,474.6,175.0,520.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
765,2023-10-10,HUBVC,0.0,0.00,-150.0,9.76,10.23,4.8,inf,0.0,0.0,-79.5,-79.5,0.0,0.0,-79.5,-79.5
766,2023-10-06,ASUZU,8.0,0.00,8.0,264.00,271.80,3.0,inf,0.0,2174.4,0.0,0.0,62.4,2174.4,62.4,2174.4
767,2023-10-09,ASUZU,0.0,0.00,-8.0,265.00,250.00,-5.7,inf,0.0,0.0,-126.4,-126.4,-0.0,0.0,-126.4,-126.4
768,2023-10-09,HEKTS,250.0,0.00,250.0,24.08,24.22,0.6,inf,0.0,6055.0,0.0,0.0,35.0,6055.0,35.0,6055.0
769,2023-10-10,HEKTS,250.0,0.00,0.0,24.90,24.70,-0.8,inf,0.0,6175.0,0.0,0.0,-50.0,6175.0,-50.0,6175.0

In [57]:
price_hourly.query("ticker == 'XU100'").tail(21)

           open     high      low    close ticker                date
709787  8463.87  8464.93  8463.67  8464.93  XU100 2023-10-06 18:00:00
709788  8464.93  8300.69  8300.69  8300.69  XU100 2023-10-09 09:00:00
709789  8298.18  8383.53  8270.10  8340.03  XU100 2023-10-09 10:00:00
709790  8339.51  8377.95  8319.44  8324.65  XU100 2023-10-09 11:00:00
709791  8324.38  8357.22  8320.78  8354.46  XU100 2023-10-09 12:00:00
709792  8354.14  8364.29  8342.57  8358.66  XU100 2023-10-09 13:00:00
709793  8358.80  8372.45  8348.12  8357.96  XU100 2023-10-09 14:00:00
709794  8357.46  8370.79  8298.27  8316.89  XU100 2023-10-09 15:00:00
709795  8317.43  8357.70  8315.25  8349.19  XU100 2023-10-09 16:00:00
709796  8350.12  8353.44  8197.89  8205.53  XU100 2023-10-09 17:00:00
709797  8206.12  8206.12  8193.44  8193.44  XU100 2023-10-09 18:00:00
709798  8193.44  8304.81  8304.81  8304.81  XU100 2023-10-10 09:00:00
709799  8318.90  8386.31  8318.90  8375.68  XU100 2023-10-10 10:00:00
709800  8375.54  8415.78  8363.25  8403.71  XU100 2023-10-10 11:00:00
709801  8404.55  8418.62  8392.10  8403.55  XU100 2023-10-10 12:00:00
709802  8403.39  8408.53  8348.06  8365.51  XU100 2023-10-10 13:00:00
709803  8364.80  8393.04  8347.17  8366.96  XU100 2023-10-10 14:00:00
709804  8366.42  8405.84  8365.10  8397.36  XU100 2023-10-10 15:00:00
709805  8396.75  8425.84  8377.18  8395.88  XU100 2023-10-10 16:00:00
709806  8396.75  8450.83  8396.00  8438.83  XU100 2023-10-10 17:00:00
709807  8438.66  8442.79  8438.26  8442.79  XU100 2023-10-10 18:00:00